### ISSUE TITLE
Camera's not showing under Nearby acessories

### ISSUE THREAD

**Issue by mattmartinez2006** [Brandawg93/homebridge-nest-cam2#10]
I was able to add the accessories last night but after they were added, in Homekit they showed as No Response on the screen display. I then deleted the application from Homebridge and tired to add them again... Sadly they aren't showing up as discoverable under Near by accessories. How do I see them again on near by accessories? How do I show images? (i am using a raspberry pi and installed Camera FFMPEG Omx but still didnt see a change when I added h264_omx

**Comment by Brandawg93** [comment]
Make sure you are inside your network and not using a VPN when you add the cameras. You may need to delete your homebridge cache usually found in `/home/pi/.homebridge`. Also, the images showing is a hit and miss for me as well. It seems to be a homekit issue. In testing, homebridge successfully grabs an image, but homekit just doesn't do anything with it. The camera feed itself should still work, though.

**Comment by mattmartinez2006** [comment]
Looks like when I deleted a file called cachedAccessories and then restarted Homebridge then it would allow me to add the cameras again
