### ISSUE TITLE
More "not responding" instances since after v0.0.2

### ISSUE THREAD

**Issue by ericdhkim** [Brandawg93/homebridge-nest-cam2#11]
Hey,

Thanks for all the updates; really great to see this plugin getting all this love. 
After updating yesterday to v0.0.2, I'm noticing that my cameras are more often than not showing "not responding" when I click into the camera. Checking my homebridge logs, I don't see any errors though. Also I know on the main description you identified that thumbnails not refreshing is an issue with the iPhone, but actually before v0.0.2 my thumbnails (as in before clicking into the camera in the Home app) updated quote frequently (in the bottom right corner, I would see how many seconds elapsed since the past update). However ever since v0.0.2 and now I'm on v1.1.0, my thumbnails don't update at all and when I click into the camera, I get the spinning wheel and then the "no response" message. Cameras are on in nest app of course. 

Any ideas?

**Comment by ericdhkim** [comment]
I'm noticing that the "streaming" switch doesn't seem to sync with when the camera is turned on and off in the nest app. As in if I turn the camera on via nest app, the streaming switch toggle is still in the off position. Manually flipping the switch to on sometimes seems to help to bring the live feed into the home app, but not always

**Comment by Brandawg93** [comment]
Check #12 for video thumbnails. I'll be updating about it in there. Also, good catch on the switch. It checks at plugin startup but never after that. I'll work on that one.

**Comment by Brandawg93** [comment]
The enabled/disabled switch should now work properly in v1.1.1. Try it out and let me know. Thanks for the bug report!

**Comment by ericdhkim** [comment]
Yes switch seems to be working now!
