### ISSUE TITLE
Video Thumbnail Only Updates only until version 0.0.26

### ISSUE THREAD

**Issue by muzzymate** [Brandawg93/homebridge-nest-cam2#12]
Updated from version 0.0.26 to 1.1.0 today. When utilizing version 1.1, the video thumbnail no longer updates. The video stream works perfectly if I tap on it and will start playing right away. I tried rebooting phone and my two Catalina Macs with the Home app but that does not resolve the issue. Going back to version 0.0.26 and restarting the Homebridge instance corrects the issue and the thumbnail will update itself once a minute. The issue also occurs if I try to update to version 0.0.27.

I am hosting Homebridge on a Windows 10 computer with npm 6.13.4 and node 12.16.1. Each plugin I run has it's own Homebridge instance, so only nest-cam2 and config-ui-x run in this instance. 

Any troubleshooting thoughts?

    "plugins": [
        "homebridge-nest-cam2",
        "homebridge-config-ui-x"
    ],

**Comment by Brandawg93** [comment]
Others are having this issue as well. For now I'll revert back to how it used to handle thumbnails. Fix coming soon.

**Comment by Brandawg93** [comment]
The code has been reverted in v1.1.1. Please try it out and let me know. For some reason, my old iPhone never updates the snapshots so it's very difficult for me to test.

**Comment by ericdhkim** [comment]
Just updated. Not seeing improvement on the thumbnails :/

**Comment by Brandawg93** [comment]
Interesting. It was completely hit or miss for me using the old plugin and this new one. Sometimes it would refresh perfectly every 10 seconds, and others it wouldn't do anything. I can confirm that the plugin is successfully getting an image and passing it to homebridge. From there, I have no idea what's happening to it.

**Comment by muzzymate** [comment]
Can confirm 1.1.1 did not seem to correct the thumbnail refresh issue for me after letting it sit for a few moments. Reverting back to 0.0.26, it will pull a thumbnail once a minute (I'm not on the same LAN, if that determines timing). Please let me know if there is any debug material I could pull to help out, as I won't be any good with coding.

**Comment by Brandawg93** [comment]
This should actually be fixed in v1.1.2. If someone can verify, I'll close this.

**Comment by muzzymate** [comment]
This fixed it up for me. Awesome! Appears to be working now and the thumbnail is changing once a minute. Thank you!!!
