### ISSUE TITLE
Cameras not showing in HomeKit

### ISSUE THREAD

**Issue by 13mralex** [Brandawg93/homebridge-nest-cam2#2]
When I go to add my cameras to Home, they do not appear. They have successfully been discovered and created in my log, but don't show up beyond that. I do get a warning, but I don't know if it's related or not.
`(node:14112) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`
I have added another camera accessory from a different plugin to the config to make sure cameras were being exposed at all, and it works fine. I am running on Windows.

**Comment by Brandawg93** [comment]
Does it give you a bigger stack trace? I don't use the `Buffer()` function anywhere but am using the newer Buffer methods.

**Comment by 13mralex** [comment]
I'm not sure...how do I check?

**Comment by Brandawg93** [comment]
You can run Homebridge in debug mode using `-D`. If you can, try running Homebridge in a docker container and see if that works for you. I've updated the README to include [instructions](https://github.com/Brandawg93/homebridge-nest-cam2#run-homebridge-using-docker).

**Comment by 13mralex** [comment]
I ran it with `-D`, no errors or anything else turned up. The link you provided says that Homebridge will not run on a Windows Docker instance, so I don't think I can do that.

**Comment by Brandawg93** [comment]
The latest commit gives better debug logging. Try running `-D` now and see what comes up for ffmpeg.

**Comment by Brandawg93** [comment]
If this is no longer an issue, please let me know and I will close it.
