### ISSUE TITLE
Feature Request: Option to remove motion sensor accessory

### ISSUE THREAD

**Issue by ericdhkim** [Brandawg93/homebridge-nest-cam2#20]
Hey,

Thanks for all the updates (by the way I don't know how to categorize this as a feature request and not an issue so apologies if I did that incorrectly).
I saw that recently we got the ability to use motion sensing if the camera is turned on. I was wondering if down the line it'd be possible for us to change the config.json to turn off those motion sensing accessories? I already have motion sensors from different smart home platforms in many of my rooms so this one is kind of redundant.

Thanks again!

**Comment by Brandawg93** [comment]
You don’t have to use the motion sensors. You now have the option to use them if you want to, but it is disabled by default in the Home app. You can enable it by going to the camera’s settings > notifications, then enabling it.

**Comment by ericdhkim** [comment]
Sorry if my oriignla post wasn't clear. I did see that you can disable motivations, I meant it'd be nice if there was a way to disable the entire motion sensor accessory (like the actual tile in the Home app). By default you wouldn't see the motion sensor separately but I actually ungrouped the camera accessory so that I can have the "Strreaming" switch on its own to make turning the camera on and off 1-click. The downside to that is that Home app doesn't let me regroup the motion sensor and the actual camera feed back together (it's all or nothing for grouping or separating). That's why I was wondering if there could be a way to just disable the motion sensor accessory. Hope that makes more sense.

**Comment by Brandawg93** [comment]
Ah. That makes sense. I'll add it to the list of stuff to do.

**Comment by ericdhkim** [comment]
Awesome thank you!

**Comment by Brandawg93** [comment]
This is added in v1.1.7. Check the README for instructions.
