### ISSUE TITLE
Add [videoProcessor] support For ffmpeg permission issue

### ISSUE THREAD

**Issue by wangsu** [Brandawg93/homebridge-nest-cam2#21]
always getting this error when using windows system (Windows 10 with ffmpeg installed and added to path):

`
Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

repo homebridge-camera-ffmpeg has similar error but could be fixed by giving exact path of ffmpeg.exe

`
"videoProcessor": "C:\\Softwares\\ffmpeg\\bin\\ffmpeg.exe"
`

hopefully this repo could add this configuration parameter too.

**Comment by Brandawg93** [comment]
v1.1.8 should fix this as it now uses [ffmpeg-for-homebridge](https://github.com/homebridge/ffmpeg-for-homebridge) to control where the exe is. If you are still having issues, feel free to open an issue there.
