### ISSUE TITLE
Add Nest Cam Accessories

### ISSUE THREAD

**Issue by ljhardy** [Brandawg93/homebridge-nest-cam2#27]
Hi - I installed your plugin successfully, activated and set up the appropriate Google credentials.  In my log I see (I'm using HOOBS):

[Homebridge] [3/29/2020, 11:00:41 AM] [Nest-cam] Create camera - Family Room Cam
[Homebridge] [3/29/2020, 11:00:41 AM] [Nest-cam] Create camera - Front Door Cam
[Homebridge] [3/29/2020, 11:00:41 AM] [Family Room Cam] is running on port 36313.
[Homebridge] [3/29/2020, 11:00:41 AM] [Front Door Cam] is running on port 34691.

However, I can't see these accessories anywhere to add to any Rooms, they do not show up in Unassigned Accessories.   I'm sure that I'm missing something basic. ;-)

**Comment by Brandawg93** [comment]
The cameras need to be setup separately from homebridge. You essentially have to add them as if you were adding your bridge again.

**Comment by ljhardy** [comment]
Would I expect to see these cameras reflected back into Homebridge after adding them in Apple Home?

**Comment by Brandawg93** [comment]
According to your logs, your cameras are already in homebridge. You just have to manually add them to the home app.

**Comment by ljhardy** [comment]
Thanks. I manually added them to the home app. They’re showing up in the homebridge log but not in the UI to add as accessories.

**Comment by Brandawg93** [comment]
Try deleting your accessories and persist folders. You may have to add all your accessories again but that usually does the trick.

**Comment by ljhardy** [comment]
Thanks!  I'll give it a try.

**Comment by Brandawg93** [comment]
If you have any other issues, feel free to reach out on [discord](https://discord.gg/pc2pqmh).
