### ISSUE TITLE
accessory already added

### ISSUE THREAD

**Issue by kylegrieder** [Brandawg93/homebridge-nest-cam2#29]
When using Google Credentials to login, and using homebridge-nest for thermostat and protect usage, together with this plugin, I'm unable to add the camera to Homekit through the Home app. I use the default Homebridge code/QR and I get, "Accessory already added". Not sure what the potential issue could be.

**Comment by Brandawg93** [comment]
If you copied your credentials from homebridge-nest, make sure you change the name of the platform from “nest” to “nest-cam”.

**Comment by kylegrieder** [comment]
I only copied the `googleAuth` object, not the entire config. Below are configs for `Nest` and `Nest-cam`

`      {
            "platform": "Nest",
            "googleAuth": {
                "issueToken":  "<redacted>",
                "cookies": "<redacted>",
                "apiKey": "<redacted>"
            },
            "options": [
                "Thermostat.SeparateBuiltInTemperatureSensor.Enable"
            ]
        },
        {
            "platform": "Nest-cam",
            "googleAuth": {
                "issueToken":  "<redacted>",
                "cookies": "<redacted>",
                "apiKey": "<redacted>"
            },
            "ffmpegCodec": "libx264",
            "options": {
                "motionDetection": true,
                "streamingSwitch": true,
                "pathToFfmpeg": "ffmpeg"
            },
        },
`

**Comment by Brandawg93** [comment]
Try deleting your `accessories` and `persist` folders. It could be that homebridge has cached an older version of the camera.

**Comment by Brandawg93** [comment]
#34

**Comment by kylegrieder** [comment]
thanks for fixing this. deleting my `acccessories` and `persist` folders did end up fixing it, but it also ended up being a bit of a pain. I had to remove my old homebridge `bridge` and then re-add it along with all of my other homebridge accessories. But everything is working great now! thanks for the help.
