### ISSUE TITLE
ERR_STREAM_DESTROYED

### ISSUE THREAD

**Issue by karad0** [Brandawg93/homebridge-nest-cam2#3]
Hi,
With this nest-cam2 I have an error.
I use h264_omx,
with nest-cam, I didn't have error.

Sat, 25 Jan 2020 11:44:27 GMT Accessory [Backyard] Processing characteristic set: [{"aid":1,"iid":23,"value":"ARBbtp/vDqtIWZgeri24SYdnAxkBAQACDDE5Mi4xNjguMy43MQMC0dQEAlHOBCUCEJMRWxA+gt1uUe1LXtu5EE4DDpRHHvqCdaYgvz9JyqtnAQEABSUCEMdpVeZjF7gfZaKiMUmm5XEDDp6fmZSFQjmeMVasB234AQEA"}]
Sat, 25 Jan 2020 11:44:27 GMT Accessory [Backyard] Setting Characteristic "Setup Endpoints" to value ARBbtp/vDqtIWZgeri24SYdnAxkBAQACDDE5Mi4xNjguMy43MQMC0dQEAlHOBCUCEJMRWxA+gt1uUe1LXtu5EE4DDpRHHvqCdaYgvz9JyqtnAQEABSUCEMdpVeZjF7gfZaKiMUmm5XEDDp6fmZSFQjmeMVasB234AQEA
Sat, 25 Jan 2020 11:44:27 GMT StreamController
Session:  <Buffer 5b b6 9f ef 0e ab 48 59 98 1e ae 2d b8 49 87 67>
ControllerAddress:  192.168.3.71
VideoPort:  54481
AudioPort:  52817
Video Crypto:  0
Video Master Key:  <Buffer 93 11 5b 10 3e 82 dd 6e 51 ed 4b 5e db b9 10 4e>
Video Master Salt:  <Buffer 94 47 1e fa 82 75 a6 20 bf 3f 49 ca ab 67>
Audio Crypto:  0
Audio Master Key:  <Buffer c7 69 55 e6 63 17 b8 1f 65 a2 a2 31 49 a6 e5 71>
Audio Master Salt:  <Buffer 9e 9f 99 94 85 42 39 9e 31 56 ac 07 6d f8>
Sat, 25 Jan 2020 11:44:27 GMT EventedHTTPServer [::ffff:192.168.3.71] HTTP Response is finished
Sat, 25 Jan 2020 11:44:27 GMT EventedHTTPServer [::ffff:192.168.3.71] HTTP request: /characteristics?id=1.23
Sat, 25 Jan 2020 11:44:27 GMT HAPServer [51:C4:89:E4:E9:21] HAP Request: GET /characteristics?id=1.23
Sat, 25 Jan 2020 11:44:27 GMT Accessory [Backyard] Getting value for Characteristic "Setup Endpoints"
Sat, 25 Jan 2020 11:44:27 GMT StreamController Setup Read
Sat, 25 Jan 2020 11:44:27 GMT Accessory [Backyard] Got Characteristic "Setup Endpoints" value: ARBbtp/vDqtIWZgeri24SYdnAgEAAxkBAQACDDE5Mi4xNjguMy41NwMC0dQEAlHOBCUBAQACEJMRWxA+gt1uUe1LXtu5EE4DDpRHHvqCdaYgvz9JyqtnBSUBAQACEMdpVeZjF7gfZaKiMUmm5XEDDp6fmZSFQjmeMVasB234BgRJ+RQABwRUUi8A
Sat, 25 Jan 2020 11:44:27 GMT EventedHTTPServer [::ffff:192.168.3.71] HTTP Response is finished
Sat, 25 Jan 2020 11:44:27 GMT EventedHTTPServer [::ffff:192.168.3.71] HTTP request: /characteristics
Sat, 25 Jan 2020 11:44:27 GMT HAPServer [51:C4:89:E4:E9:21] HAP Request: PUT /characteristics
Sat, 25 Jan 2020 11:44:27 GMT Accessory [Backyard] Processing characteristic set: [{"aid":1,"iid":21,"value":"ARUCAQEBEFu2n+8Oq0hZmB6uLbhJh2cCNAEBAAIJAQECAgECAwEAAwsBAgAFAgLQAgMBHgQXAQFjAgTfKznMAwIrAQQEAAAAPwUCYgUDLAEBAgIMAQEBAgEAAwEBBAEeAxYBAW4CBCZcE3UDAhgABAQAAKBABgENBAEA"}]
Sat, 25 Jan 2020 11:44:27 GMT Accessory [Backyard] Setting Characteristic "Selected RTP Stream Configuration" to value ARUCAQEBEFu2n+8Oq0hZmB6uLbhJh2cCNAEBAAIJAQECAgECAwEAAwsBAgAFAgLQAgMBHgQXAQFjAgTfKznMAwIrAQQEAAAAPwUCYgUDLAEBAgIMAQEBAgEAAwEBBAEeAxYBAW4CBCZcE3UDAhgABAQAAKBABgENBAEA
Sat, 25 Jan 2020 11:44:27 GMT StreamController Write SelectedStreamConfiguration
[1/25/2020, 12:44:27 PM] [Nest-cam] waiting for socket to connect
[1/25/2020, 12:44:27 PM] [Nest-cam] [NexusStreamer] Connected
[1/25/2020, 12:44:28 PM] [Nest-cam] [NexusStreamer] OK
[1/25/2020, 12:44:28 PM] [Nest-cam] [NexusStreamer] Redirect
[1/25/2020, 12:44:28 PM] [Nest-cam] [NexusStreamer] Redirecting...
[1/25/2020, 12:44:28 PM] [Nest-cam] waiting for socket to connect
[1/25/2020, 12:44:28 PM] [Nest-cam] [NexusStreamer] Disconnected
[1/25/2020, 12:44:28 PM] [Nest-cam] [NexusStreamer] Connected
[1/25/2020, 12:44:29 PM] [Nest-cam] [NexusStreamer] OK
[1/25/2020, 12:44:29 PM] [Nest-cam] [NexusStreamer] Playback Begin
[1/25/2020, 12:44:35 PM] [Nest-cam] ERR_STREAM_DESTROYED
[1/25/2020, 12:44:35 PM] [Nest-cam] [NexusStreamer] Disconnected

**Comment by Brandawg93** [comment]
Are you still getting this error (ERR_STREAM_DESTROYED) or is it working for you now? It does this to me every so often because my pi4 can't handle the encode, but most of the time, it works.

**Comment by karad0** [comment]
Yes same error. 
It’s strange. I have try to recompil ffmpeg. But same. 
I use libx264 but it’s very slow. 
Before i used nest cam omx without any problem. 
You have see here in different tree. He have to do update. 
https://github.com/schmittx/homebridge-nest-cam/tree/accessory-information-nest-hello-resolution

**Comment by karad0** [comment]
And in this this tree
https://github.com/schmittx/homebridge-nest-cam/tree/dev
I don't if change anythings!

**Comment by Brandawg93** [comment]
Both of those have been integrated. Let me know if it works!

**Comment by karad0** [comment]
you update this?
https://github.com/schmittx/homebridge-nest-cam/commit/6794d92bdb1686228b71e6e62212fed73c9298fc

https://github.com/schmittx/homebridge-nest-cam/commit/8fdd980d859d8b7efb32e317a9d2083a5a3efbe5

**Comment by Brandawg93** [comment]
Correct. Those are in there. Some of those changes aren't needed, but the ones that matter were changed.

**Comment by karad0** [comment]
Ok,
with libx264 it's ok.
Juste outdoor model is not recognize.
![Capture d’écran   2020-01-26 à 16 37 32](https://user-images.githubusercontent.com/8874409/73137713-840f0580-405b-11ea-8e68-b3c1c0b0eb62.png)

**Comment by karad0** [comment]
I don't use homebridge-config-ui so I can't say if it's ok

**Comment by Brandawg93** [comment]
I've added all camera types [here](https://github.com/Brandawg93/homebridge-nest-cam2/blob/master/index.js#L7). I didn't publish this to npm since the current version still works just fine. If you want to try this out, uninstall this plugin with `npm -g uninstall homebridge-nest-cam2` and install the github version with `npm -g i git+https://github.com/Brandawg93/homebridge-nest-cam2`.

**Comment by karad0** [comment]
It's very good.
I think, I have resolved my problem with omx in config.txt.
before gpu_mem=16
After gpu_mem=128
And now it's ok.
I closed the issue!

**Comment by karad0** [comment]
Just ask,
you think if it's possible to add a rich notification when I have a motion sensor?
https://github.com/KhaosT/homebridge-camera-ffmpeg/commit/282fca44f5e219080633c878e201490d912aab75
