### ISSUE TITLE
Re add cam

### ISSUE THREAD

**Issue by CypressGTX** [Brandawg93/homebridge-nest-cam2#31]
**Before Submitting**
Please check [Nest Status](https://status.nest.com/) before submitting a bug.

**Describe the bug**
My Nest cam indoor and Hello are crashed and I had to delete the camera's from Apple Homekit. (I thought)
After deleting the camera's I create a new api cookie etc from nest.google
In the command line the plugin told me to (re) -add the camera's with the PIN to HomeKit, but HomeKit can't find the camera's for the second time. 

**what I've tried:**
Uninstall the plugin but it doesn't work.
Install the plugin
Create new cookie files api from nest.com
restart HomeBridge
restart RPi

is there an easy solution for? I don't want to lose my configuration and setup. 

Thanks guys! I love the plugin :)

**Comment by Brandawg93** [comment]
Try deleting your `persist` and `accessories ` folders. You may have to re-add your accessories, but you won’t lose your config.

**Comment by CypressGTX** [comment]
Yes clear it works, the ticket can be closed. 
Thank you! 


What i had to do (for other people)

- Browse to your homebridge folder
cd /home/pi/.homebridge

- Delete the folders accessories and persist 
sudo rm -r persist/
sudo rm -r accessories/

- Go to your Apple Home app
Delete the homebridge from your Apple home app

- restart the whole machine For me the raspberry

- start homebridge

- re add the homebridge to Apple Home

- add with the same pin the camera’s to Apple Home

———
Config file is still the same, the only thing what you need to do is re-add bulbs from homebridge to scènes Again.
