### ISSUE TITLE
Home app can't see all cameras that Nest-Cam2 has found

### ISSUE THREAD

**Issue by asymptote71** [Brandawg93/homebridge-nest-cam2#32]
**Before Submitting**
Please check [Nest Status](https://status.nest.com/) before submitting a bug.

**Describe the bug**

**To Reproduce**
1. 

**Expected behavior**

Include with your bug report this version info:
```
node --version
homebridge --version
```

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest-cam2`

Also include debug log output from startup through seeing the issue:
`homebridge -D`

**Comment by Brandawg93** [comment]
Try deleting your `persist` and `accessories` folders. you may have to re-add all cameras but this fixes most issues.

**Comment by Brandawg93** [comment]
This will be resolved if you update to 2.0.0.
