### ISSUE TITLE
Add ability to toggle Nest Cam on/off

### ISSUE THREAD

**Issue by jqnatividad** [Brandawg93/homebridge-nest-cam2#5]
Thanks for all the great work reverse-engineering the NEST API!

It'd be great if you can also expose a toggle switch in Homekit for the camera.

**Comment by Brandawg93** [comment]
Done! This is in 0.25.0. You can find the toggle under _Accessories_ in the camera settings.

**Comment by jqnatividad** [comment]
Awesome! Can confirm it works like a charm. Thanks!
