### ISSUE TITLE
Status of WIP motion detection

### ISSUE THREAD

**Issue by jqnatividad** [Brandawg93/homebridge-nest-cam2#6]
I see there’s some code for motion detection tagged WIP... any chance of enabling it sooner than later?

**Comment by Brandawg93** [comment]
Unfortunately not. All api data is based on https://home.nest.com which never receives motion notifications and I can't find any flag on any other api call that would let me know if motion was detected. Nest uses both Apple's and Google's push notification services for the mobile apps, but I can't inspect their network traffic like I can the website. If someone finds a way to get motion notifications via an api call, I'd definitely make it happen.

**Comment by karad0** [comment]
Hi,
With other motion detect you can to do this
KhaosT/homebridge-camera-ffmpeg@282fca4

**Comment by Brandawg93** [comment]
That is a workaround for picture notifications of motion, not motion in general. homebridge-camera-ffmpeg assumes that the camera sends an api call stating that motion is detected. Nest does not send an api call to the website for motion. Rather they rely on Apple and Google's push notification services which the plugin cannot use.

**Comment by Brandawg93** [comment]
Motion detection is now live in v1.1.0!
