### ISSUE TITLE
Second camera not found in the home app

### ISSUE THREAD

**Issue by Mattia0880** [Brandawg93/homebridge-nest-cam2#7]
Good evening, I have a nest account with two houses, there are 2 cameras, an indoor cam and a nest hello.  I configured the plugin correctly and when I start homebridge it tells me that it created the two "office" and "door" cameras with two different ports and tells me to add them to the home app with the configuration code.  The problem is that as soon as I go to add a new accessory to the home app I only find the nest hello so "door" and the other "office" camera won't find me even after hours.  Before adding the nest hello the "office" camera worked in homekit then I removed everything and reaching everything I can no longer add the second one.  Maybe it only supports one camera and can't add two?

**Comment by Brandawg93** [comment]
I’m currently using two cameras, an indoor and outdoor and both work but they are both at the same location. Since I don’t have a multi-location account, it’s hard for me to test it. I’ll leave this issue open and if anyone using multiple cameras in multiple locations can comment here if it’s working or not let us know.

**Comment by Mattia0880** [comment]
Thanks, now doing various tests even restarting homebridge no longer finds either of the two cameras in the home app even if in the homebridge log it tells me that they are ready to be added.  Is there any way to reset everything?

**Comment by Brandawg93** [comment]
I would ask that over at the [Homebridge Github](https://github.com/nfarina/homebridge). Not sure what I can do from a plug-in standpoint on a full reset.

**Comment by Gamer106** [comment]
I'm also having trouble reaching my second cam. running homebridge shows that it connects, disconnects, redirects, then connects when I view cam 1, but when I leave and it disconnects cam 1, I try to view cam 2 and it doesn't attempt to do anything. Cam 1 works again with the same logs when I go back to view it.

**Comment by Brandawg93** [comment]
try running homebridge with the debug option "-D" and post the output here.

**Comment by Gamer106** [comment]
Well, I did that and it's working now. How long before the camera is turned on does it take for the Home app to realize it's on? I quit the app after viewing the camera in the Nest app, then opened the Home app and it was not responding. It's been about 10 minutes now and it's responding in Home.

**Comment by Brandawg93** [comment]
@Gamer106, try the new release, adc5b6cc32fb7d71af1b32e2c1e12d16fc840fc4. It should be more stable.

@Mattia0880, are you still having this issue?

**Comment by Mattia0880** [comment]
Already before the update I had solved the problems with the cameras by reinstalling homebridge on raspberry now I added them both and they work.  The problem is that even after the update, the streaming of the rooms seems to slow down and is very late

**Comment by Brandawg93** [comment]
That sounds similar to #8. Unfortunately, there isn't much I can do. Raspberry Pi's are not very powerful when it comes to transcoding video. The best advice I can offer is to make sure you are using the `h264_omx` codec mentioned in the [README](https://github.com/Brandawg93/homebridge-nest-cam2#installation).

**Comment by Gamer106** [comment]
[2/20/2020, 1:31:56 PM] [Nest-cam] Unexpected API Error - 404
[2/20/2020, 1:32:02 PM] [Nest-cam] [NexusStreamer] Connected
[2/20/2020, 1:32:02 PM] [Nest-cam] waiting for authorization
[2/20/2020, 1:32:02 PM] [Nest-cam] ffmpeg version N-94383-g3883c9d147 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr/local --arch=armel --target-os=linux --enable-omx-rpi --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-mmal --enable-libx264 --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
  libavutil      56. 32.100 / 56. 32.100
  libavcodec     58. 55.100 / 58. 55.100
  libavformat    58. 30.100 / 58. 30.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.100 /  7. 58.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100

[2/20/2020, 1:32:02 PM] [Nest-cam] [NexusStreamer] OK
[2/20/2020, 1:32:02 PM] [Nest-cam] [NexusStreamer] Redirect
[2/20/2020, 1:32:02 PM] [Nest-cam] [NexusStreamer] Redirecting...
[2/20/2020, 1:32:02 PM] [Nest-cam] waiting for socket to connect
[2/20/2020, 1:32:02 PM] [Nest-cam] [NexusStreamer] Disconnected
[2/20/2020, 1:32:02 PM] [Nest-cam] [NexusStreamer] Connected
[2/20/2020, 1:32:02 PM] [Nest-cam] [NexusStreamer] OK
[2/20/2020, 1:32:03 PM] [Nest-cam] [NexusStreamer] Playback Begin
[2/20/2020, 1:32:08 PM] [Nest-cam] Input #0, h264, from 'pipe:':
  Duration: N/A, bitrate: N/A

**Comment by Brandawg93** [comment]
That may be a Nest issue. 404 means the link provided was not found. Meaning the access token probably came back with a bad response. I would suggest going through getting the googleAuth options again and then try it out.

**Comment by Brandawg93** [comment]
#9

**Comment by Mattia0880** [comment]
I tried to put h264_omx it is more fluid and with less delay, however, it loses some video quality.  I have a raspberry pi3, could the pi4 be fine?  what advice for cam stream, which device works well?  I also tried with a nas synology using the docker but on homebridge it doesn't work and on hobbs it tells me access denied for this the raspberry

**Comment by Brandawg93** [comment]
I'm using a Raspberry Pi 4 and it's working just fine, but it is a little slow. One day, I hope to remove the need to encode. Technically, the Nest app is receiving the correct type of stream that an iOS device needs without transcoding meaning that there is some way to ask Nest for the correct stream, but I can't decompile the Nest app like I can the Nest website to figure out how to.

**Comment by Brandawg93** [comment]
@Mattia0880, could you try [this](https://github.com/Brandawg93/homebridge-nest-cam2/issues/9#issuecomment-589289241) for me? Instead of Request it should say "Get request sent to x". Can you tell me what x is?

**Comment by Brandawg93** [comment]
Since the initial issue is resolved, I'm going to close this one. @Finch106, I'll continue to work on your issue in #9. If you are able, try [this](https://github.com/Brandawg93/homebridge-nest-cam2/issues/9#issuecomment-589289241) and post your results in there.
