### ISSUE TITLE
Option to allow video capture at 5 fps (or lower) to reduce CPU consumption in Raspberry PI's

### ISSUE THREAD

**Issue by harrywer** [Brandawg93/homebridge-nest-cam2#8]
Can we have an option to allow video capture at 5 fps (or lower) to reduce CPU consumption in Raspberry PI's ?

**Comment by Brandawg93** [comment]
I tested fps rates on a Raspberry Pi. It isn't the fps that is killing the pi, rather it's the encoding using libx264. Try changing the ffmpegCodec to h264_omx as mentioned in the [README](https://github.com/Brandawg93/homebridge-nest-cam2#installation).
