### ISSUE TITLE
API error after updating to v0.0.27

### ISSUE THREAD

**Issue by ericdhkim** [Brandawg93/homebridge-nest-cam2#9]
Updated to v0.0.27 about an hour ago. Started seeing 

> [Nest-cam] Unexpected API Error - 404

Tried restarting phone, removed homebridge from Apple Home then re-added. Still seeing the errors show up in Homebridge logs and while I can add the cameras okay, the cameras don't return anything in the app, the thumbnails show a "no response" error.

**Comment by Brandawg93** [comment]
Others are getting the same error so it's not just you. I'm trying to figure out how to reproduce the error as it's not happening to me. Looking into it.

**Comment by Brandawg93** [comment]
My initial guess is that there is a conflicting package. I'm using docker, so whenever I modify packages, they are automatically added or removed as needed. Try removing bluebird, request, and request-promise and let me know if it doesn't work.

`npm -g uninstall bluebird request request-promise`

**Comment by ericdhkim** [comment]
> My initial guess is that there is a conflicting package. I'm using docker, so whenever I modify packages, they are automatically added or removed as needed. Try removing bluebird, request, and request-promise and let me know if it doesn't work.
> 
> `npm -g uninstall bluebird request request-promise`

just tried this, rebooted server and doesn't seem to have helped :/

**Comment by Brandawg93** [comment]
2cdf1dbe9ec5f7684412d5cd11ba0da66cb342c8 has better debug logging for the API calls. Try using the github version of the plugin by uninstalling it first, then installing via `npm -g i git+https://github.com/Brandawg93/homebridge-nest-cam2/` then run homebridge in debug mode `homebridge -D`. There should be a line just before the errors that start with "Request: ". Post that here (without your access token) so I can see where your requests are going.

**Comment by Brandawg93** [comment]
After doing some digging, I've found that this is definitely a Nest issue. It even happens on their own website. It shouldn't affect the functionality of the camera, but you may see 404 errors within homebridge. I'll leave this issue open for visibility for a while.

**Comment by Brandawg93** [comment]
Fixed in v0.28.0. The errors occurred when a nest cam was turned off and homebridge was trying to get the thumbnail image.
